FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y autoconf gettext libtool make

COPY . /repo
WORKDIR /repo
ENV LD_LIBRARY_PATH=/repo/.libs/
RUN ldconfig
RUN ./autogen.sh
RUN ./configure --prefix=/install
RUN make -j8
RUN make install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
